from yacs.config import CfgNode as CN

_C = CN()

_C.TYPE = 'tipadapter'

_C.TRAINER = CN()
_C.TRAINER.MAX_EPOCH = 20
_C.TRAINER.INIT_ALPHA = 1.0
_C.TRAINER.INIT_BETA = 5.5

_C.FREQ_EVAL = 5

_C.TRAINER.OPTIM = CN()
_C.TRAINER.OPTIM.LR = 0.001
_C.TRAINER.OPTIM.CLIP = CN()
_C.TRAINER.OPTIM.CLIP.LR_VISUAL = 0.0000001
_C.TRAINER.OPTIM.CLIP.LR_TOKEN_SCALE = 1.

_C.DATALOADER = CN()
_C.DATALOADER.AUGMENT_EPOCHS = 10
_C.DATALOADER.BATCH_SIZE_CACHE = 256
_C.DATALOADER.BATCH_SIZE_TRAIN = 256
_C.DATALOADER.BATCH_SIZE_TEST = 256
_C.DATALOADER.NUM_WORKERS = 6
_C.DATALOADER.K_SHOT = 1

def get_cfg_defaults_tipadapter():
    return _C.clone()