from yacs.config import CfgNode as CN

_C = CN()
_C.TYPE = 'ce'
_C.FREQ_EVAL = 5

_C.TRAINER = CN()
_C.TRAINER.OPTIM = CN()
_C.TRAINER.OPTIM.TYPE = "sgd"
_C.TRAINER.OPTIM.LR = 0.002
_C.TRAINER.OPTIM.CLIP = CN()
_C.TRAINER.OPTIM.CLIP.LR_VISUAL = 0.000001
_C.TRAINER.OPTIM.CLIP.LR_TOKEN_SCALE = 0.0
_C.TRAINER.MAX_EPOCH = 50

_C.DATALOADER = CN(new_allowed=True)
_C.DATALOADER.BATCH_SIZE_TRAIN = 32
_C.DATALOADER.BATCH_SIZE_TEST = 100
_C.DATALOADER.NUM_WORKERS = 6
_C.DATALOADER.K_SHOT = 5

def get_cfg_defaults_ce() -> CN:
    return _C.clone()