from yacs.config import CfgNode as CN

_C = CN()

_C.TYPE = 'omaml_clip'
_C.BACKBONE = 'CLIP-RN50'

_C.TRAINER = CN()
_C.TRAINER.MAX_EPOCH = 50
_C.TRAINER.GRAD_CLIP_MAX = 1.0

_C.TRAINER.OPTIM = CN()
_C.TRAINER.OPTIM.LR_TOKEN_SCALE = 1.
_C.TRAINER.OPTIM.LR = 0.000001
_C.TRAINER.OPTIM.TOKEN_RATIO = 0.2
_C.TRAINER.OPTIM.NUM_TEMPLATES = 1
_C.TRAINER.OPTIM.LAMBDA_R = 1.0
_C.TRAINER.OPTIM.LAMBDA_O = 1.0

_C.DATALOADER = CN()
_C.DATALOADER.NUM_TASKS = 1
_C.DATALOADER.K_OBSTRUCT = 1
_C.DATALOADER.BATCH_SIZE_OBSTRUCT = 128
_C.DATALOADER.NUM_WORKERS = 8

def get_cfg_defaults_omaml_clip() -> CN:
    r'''Get a default CfgNode for OmamlCLIP
    '''
    return _C.clone()